---

# os user account to own/manage the hat application
user_name: pi
user_password: $6$6w3soatjDyf.vUpi$DfwyxKLt7.J5EuQKuNzzc63kWBItizIsI9b98A2h3KMbUzoS6de9RXEFgocqxVN2Y3YQqL34C1WCZWjZMGXQe/
user_group: pi
user_groups:
  - adm
  - audio
  - bluetooth   # access speaker
  - i2c
  - input       # access rfid reader
  - gpio
  - plugdev
  - spi
  - sudo
  - users

# application directories  
app_dir: /opt/sortinghat
app_src_dir: "{{ app_dir }}/src"
app_venv_dir: "{{ app_dir }}/venv"
